# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 14:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='trendsfull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend', models.CharField(blank=True, max_length=30)),
                ('count', models.CharField(blank=True, max_length=30)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
