# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senti', '0003_auto_20160518_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trends',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trendsfull',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tweethist',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
