# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senti', '0006_tweethist_loca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweethist',
            name='searchid',
        ),
    ]
